<?php
/*
 * Created by Martin Wernståhl on 2009-07-12.
 * Copyright (c) 2009 Martin Wernståhl.
 * All rights reserved.
 */

// Store the initial start time here for the profiler to use
$start = microtime(true);

/*
 * Remove error viewing, but let all errors be reported.
 * 
 * This is to let all errors go to Inject, making it handle them all.
 * It makes it possible to selectively log everything or nothing by
 * the custom loggers (which will be responsible for all error
 * displays).
 */
error_reporting(E_ALL | E_DEPRECATED);
ini_set('display_errors', '0');

/*
 * Include Inject core class.
 */
require './lib/Inject.php';

/*
 * Add the autoloader and error handling.
 */
Inject::init();

// Initialize the profiler
$p = new Inject_Profiler($start);


/*
 * Here you paste the code generated by Inject_Util_LoaderCache_Writer->getPHP();
 * 
 * This increases performance, as Inject won't have to search the application
 * folders for the files for each new request.
 */

/*
 * Set applicaiton paths.
 * 
 * Here you define the application paths, with the most important one first.
 */
Inject::addPaths(array('app'));
Inject::attachLogger($p);

// Run a HMVC request, so we specify controller and action
//Inject::run(new Inject_Request_HMVC('Controller_Test', 'testAction'));

Inject::run(new Inject_Request_HTTP_URI(Inject_URI::getCurrentURI()));

// let the profiler render its data
$p->display();

/* End of file index.php */
/* Location: . */